-- V13: multi-agent suggestion queue
-- Agents never mutate business tables directly. They create suggestions first;
-- users approve, dismiss, or apply those suggestions through server routes.

create table if not exists public.agent_suggestions (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    agent_type text not null check (
        agent_type in (
            'weekly_briefing',
            'task_quality',
            'accessibility_reminder',
            'workload_balance',
            'notification'
        )
    ),
    title text not null,
    summary text not null,
    severity text not null default 'info' check (
        severity in ('info', 'low', 'medium', 'high', 'critical')
    ),
    dedupe_key text,
    status text not null default 'pending' check (
        status in ('pending', 'approved', 'dismissed', 'applied')
    ),
    target_table text,
    target_id bigint,
    payload jsonb not null default '{}'::jsonb,
    evidence jsonb not null default '{}'::jsonb,
    created_by text,
    reviewed_by text,
    reviewed_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists agent_suggestions_team_status_idx
    on public.agent_suggestions (team_id, status, created_at desc);

create index if not exists agent_suggestions_agent_type_idx
    on public.agent_suggestions (team_id, agent_type, created_at desc);

create index if not exists agent_suggestions_target_idx
    on public.agent_suggestions (target_table, target_id);

create unique index if not exists agent_suggestions_dedupe_key_idx
    on public.agent_suggestions (team_id, dedupe_key);

alter table public.agent_suggestions enable row level security;

drop policy if exists "agent suggestions readable by team members" on public.agent_suggestions;
create policy "agent suggestions readable by team members"
on public.agent_suggestions
for select
to authenticated
using (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_suggestions.team_id
          and p.email = auth.jwt() ->> 'email'
    )
);

drop policy if exists "agent suggestions insertable by team members" on public.agent_suggestions;
create policy "agent suggestions insertable by team members"
on public.agent_suggestions
for insert
to authenticated
with check (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_suggestions.team_id
          and p.email = auth.jwt() ->> 'email'
    )
);

drop policy if exists "agent suggestions reviewable by admins" on public.agent_suggestions;
create policy "agent suggestions reviewable by admins"
on public.agent_suggestions
for update
to authenticated
using (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_suggestions.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
)
with check (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_suggestions.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);
