-- V14: notification delivery history and cooldown support
-- Delivery history is separate from agent_suggestions so old suggestions can
-- remain auditable while repeated webhook sends are rate-limited by dedupe_key.

create table if not exists public.agent_notification_deliveries (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    suggestion_id bigint references public.agent_suggestions(id) on delete set null,
    agent_type text not null,
    target_table text,
    target_id bigint,
    dedupe_key text,
    channel text not null check (channel in ('personal_dm', 'team_room')),
    recipient_member text,
    payload jsonb not null default '{}'::jsonb,
    sent_by text,
    sent_at timestamptz not null default now()
);

create index if not exists agent_notification_deliveries_team_sent_idx
    on public.agent_notification_deliveries (team_id, sent_at desc);

create index if not exists agent_notification_deliveries_dedupe_sent_idx
    on public.agent_notification_deliveries (team_id, dedupe_key, sent_at desc)
    where dedupe_key is not null;

create index if not exists agent_notification_deliveries_target_idx
    on public.agent_notification_deliveries (target_table, target_id);

alter table public.agent_notification_deliveries enable row level security;

drop policy if exists "agent notification deliveries readable by team members"
on public.agent_notification_deliveries;
create policy "agent notification deliveries readable by team members"
on public.agent_notification_deliveries
for select
to authenticated
using (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_notification_deliveries.team_id
          and p.email = auth.jwt() ->> 'email'
    )
);

drop policy if exists "agent notification deliveries insertable by admins"
on public.agent_notification_deliveries;
create policy "agent notification deliveries insertable by admins"
on public.agent_notification_deliveries
for insert
to authenticated
with check (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_notification_deliveries.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);
