-- V15: member-managed Google Chat DM webhooks
-- Each member can register their own personal Google Chat webhook.
-- Notification sending uses this table for personal_dm delivery.

create table if not exists public.agent_member_webhooks (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    member text not null,
    email text not null,
    webhook_url text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (team_id, member),
    unique (team_id, email)
);

create index if not exists agent_member_webhooks_team_member_idx
    on public.agent_member_webhooks (team_id, member);

alter table public.agent_member_webhooks enable row level security;

drop policy if exists "member webhooks readable by owner or admins"
on public.agent_member_webhooks;
create policy "member webhooks readable by owner or admins"
on public.agent_member_webhooks
for select
to authenticated
using (
    email = auth.jwt() ->> 'email'
    or exists (
        select 1
        from public.players p
        where p.team_id = agent_member_webhooks.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);

drop policy if exists "member webhooks insertable by owner"
on public.agent_member_webhooks;
create policy "member webhooks insertable by owner"
on public.agent_member_webhooks
for insert
to authenticated
with check (
    email = auth.jwt() ->> 'email'
    and exists (
        select 1
        from public.players p
        where p.team_id = agent_member_webhooks.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.name = agent_member_webhooks.member
    )
);

drop policy if exists "member webhooks insertable by admins"
on public.agent_member_webhooks;
create policy "member webhooks insertable by admins"
on public.agent_member_webhooks
for insert
to authenticated
with check (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_member_webhooks.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);

drop policy if exists "member webhooks updatable by owner"
on public.agent_member_webhooks;
create policy "member webhooks updatable by owner"
on public.agent_member_webhooks
for update
to authenticated
using (email = auth.jwt() ->> 'email')
with check (email = auth.jwt() ->> 'email');

drop policy if exists "member webhooks updatable by admins"
on public.agent_member_webhooks;
create policy "member webhooks updatable by admins"
on public.agent_member_webhooks
for update
to authenticated
using (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_member_webhooks.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
)
with check (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_member_webhooks.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);
