-- V17: member-managed personal reminders
-- These are user-authored reminders, separate from agent-generated suggestions.

create table if not exists public.agent_personal_reminders (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    member text not null,
    email text not null,
    title text not null,
    note text,
    remind_at timestamptz,
    due_date date,
    status text not null default 'active' check (status in ('active', 'done', 'deleted')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists agent_personal_reminders_owner_idx
    on public.agent_personal_reminders (team_id, email, status, remind_at);

alter table public.agent_personal_reminders enable row level security;

drop policy if exists "personal reminders readable by owner or admins"
on public.agent_personal_reminders;
create policy "personal reminders readable by owner or admins"
on public.agent_personal_reminders
for select
to authenticated
using (
    email = auth.jwt() ->> 'email'
    or exists (
        select 1
        from public.players p
        where p.team_id = agent_personal_reminders.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);

drop policy if exists "personal reminders insertable by owner"
on public.agent_personal_reminders;
create policy "personal reminders insertable by owner"
on public.agent_personal_reminders
for insert
to authenticated
with check (
    email = auth.jwt() ->> 'email'
    and exists (
        select 1
        from public.players p
        where p.team_id = agent_personal_reminders.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.name = agent_personal_reminders.member
    )
);

drop policy if exists "personal reminders updatable by owner"
on public.agent_personal_reminders;
create policy "personal reminders updatable by owner"
on public.agent_personal_reminders
for update
to authenticated
using (email = auth.jwt() ->> 'email')
with check (email = auth.jwt() ->> 'email');
