-- V18: Google Calendar integration owned by the app, replacing GAS calendar reads.

create table if not exists public.agent_calendar_connections (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    member text not null,
    email text not null,
    google_email text,
    access_token text,
    refresh_token text,
    token_type text,
    scope text,
    expires_at timestamptz,
    connected_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (team_id, email),
    unique (team_id, member)
);

create table if not exists public.agent_calendar_events (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    member text not null,
    email text not null,
    google_event_id text not null,
    calendar_id text not null default 'primary',
    title text not null,
    starts_at timestamptz,
    ends_at timestamptz,
    all_day boolean not null default false,
    location text,
    html_link text,
    synced_at timestamptz not null default now(),
    unique (team_id, email, calendar_id, google_event_id)
);

create index if not exists agent_calendar_events_member_time_idx
    on public.agent_calendar_events (team_id, member, starts_at);

alter table public.agent_calendar_connections enable row level security;
alter table public.agent_calendar_events enable row level security;

-- No client policies for connections: OAuth tokens are server-only.

drop policy if exists "calendar events readable by owner or admins"
on public.agent_calendar_events;
create policy "calendar events readable by owner or admins"
on public.agent_calendar_events
for select
to authenticated
using (
    email = auth.jwt() ->> 'email'
    or exists (
        select 1
        from public.players p
        where p.team_id = agent_calendar_events.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);
