-- V19: per-member notification preferences

create table if not exists public.agent_member_notification_settings (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    member text not null,
    email text not null,
    morning_send_time time not null default '08:30',
    calendar_reminder_minutes integer not null default 15,
    morning_enabled boolean not null default true,
    calendar_reminder_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (team_id, member),
    unique (team_id, email)
);

alter table public.agent_member_notification_settings enable row level security;

drop policy if exists "notification settings readable by owner or admins"
on public.agent_member_notification_settings;
create policy "notification settings readable by owner or admins"
on public.agent_member_notification_settings
for select
to authenticated
using (
    email = auth.jwt() ->> 'email'
    or exists (
        select 1
        from public.players p
        where p.team_id = agent_member_notification_settings.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);

drop policy if exists "notification settings insertable by owner"
on public.agent_member_notification_settings;
create policy "notification settings insertable by owner"
on public.agent_member_notification_settings
for insert
to authenticated
with check (
    email = auth.jwt() ->> 'email'
    and exists (
        select 1
        from public.players p
        where p.team_id = agent_member_notification_settings.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.name = agent_member_notification_settings.member
    )
);

drop policy if exists "notification settings updatable by owner"
on public.agent_member_notification_settings;
create policy "notification settings updatable by owner"
on public.agent_member_notification_settings
for update
to authenticated
using (email = auth.jwt() ->> 'email')
with check (email = auth.jwt() ->> 'email');
