-- V21: team calendar settings and task calendar sync metadata

create table if not exists public.agent_team_calendar_settings (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    calendar_id text not null,
    connection_email text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (team_id)
);

alter table public.agent_team_calendar_settings enable row level security;

drop policy if exists "team calendar settings readable by team"
on public.agent_team_calendar_settings;
create policy "team calendar settings readable by team"
on public.agent_team_calendar_settings
for select
to authenticated
using (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_team_calendar_settings.team_id
          and p.email = auth.jwt() ->> 'email'
    )
);

drop policy if exists "team calendar settings writable by admins"
on public.agent_team_calendar_settings;
create policy "team calendar settings writable by admins"
on public.agent_team_calendar_settings
for all
to authenticated
using (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_team_calendar_settings.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
)
with check (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_team_calendar_settings.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);

alter table public.tasks
    add column if not exists show_on_team_calendar boolean not null default false,
    add column if not exists team_calendar_event_id text,
    add column if not exists team_calendar_synced_at timestamptz,
    add column if not exists team_calendar_sync_error text;

create index if not exists tasks_team_calendar_event_idx
    on public.tasks (team_id, team_calendar_event_id)
    where team_calendar_event_id is not null;
