-- V22: member calendar settings for per-member Google Calendar routing

create table if not exists public.agent_member_calendar_settings (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    member text not null,
    calendar_id text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (team_id, member)
);

alter table public.agent_member_calendar_settings enable row level security;

drop policy if exists "member calendar settings readable by team"
on public.agent_member_calendar_settings;
create policy "member calendar settings readable by team"
on public.agent_member_calendar_settings
for select
to authenticated
using (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_member_calendar_settings.team_id
          and p.email = auth.jwt() ->> 'email'
    )
);

drop policy if exists "member calendar settings writable by admins"
on public.agent_member_calendar_settings;
create policy "member calendar settings writable by admins"
on public.agent_member_calendar_settings
for all
to authenticated
using (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_member_calendar_settings.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
)
with check (
    exists (
        select 1
        from public.players p
        where p.team_id = agent_member_calendar_settings.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);

alter table public.tasks
    add column if not exists team_calendar_id text;
