-- V24: persisted accessibility mission snoozes

create table if not exists public.agent_accessibility_mission_snoozes (
    id bigint generated by default as identity primary key,
    team_id text not null default 'ud2',
    member text not null,
    email text not null,
    snooze_key text not null,
    snoozed_until timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (team_id, email, snooze_key)
);

create index if not exists agent_accessibility_mission_snoozes_owner_idx
    on public.agent_accessibility_mission_snoozes (team_id, email, snoozed_until);

alter table public.agent_accessibility_mission_snoozes enable row level security;

drop policy if exists "accessibility mission snoozes readable by owner or admins"
on public.agent_accessibility_mission_snoozes;
create policy "accessibility mission snoozes readable by owner or admins"
on public.agent_accessibility_mission_snoozes
for select
to authenticated
using (
    email = auth.jwt() ->> 'email'
    or exists (
        select 1
        from public.players p
        where p.team_id = agent_accessibility_mission_snoozes.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.role = 'admin'
    )
);

drop policy if exists "accessibility mission snoozes insertable by owner"
on public.agent_accessibility_mission_snoozes;
create policy "accessibility mission snoozes insertable by owner"
on public.agent_accessibility_mission_snoozes
for insert
to authenticated
with check (
    email = auth.jwt() ->> 'email'
    and exists (
        select 1
        from public.players p
        where p.team_id = agent_accessibility_mission_snoozes.team_id
          and p.email = auth.jwt() ->> 'email'
          and p.name = agent_accessibility_mission_snoozes.member
    )
);

drop policy if exists "accessibility mission snoozes updatable by owner"
on public.agent_accessibility_mission_snoozes;
create policy "accessibility mission snoozes updatable by owner"
on public.agent_accessibility_mission_snoozes
for update
to authenticated
using (email = auth.jwt() ->> 'email')
with check (email = auth.jwt() ->> 'email');

drop policy if exists "accessibility mission snoozes deletable by owner"
on public.agent_accessibility_mission_snoozes;
create policy "accessibility mission snoozes deletable by owner"
on public.agent_accessibility_mission_snoozes
for delete
to authenticated
using (email = auth.jwt() ->> 'email');
