-- Add and maintain normalized player/project references without removing the
-- legacy member/proj columns used by the current Next.js client.

begin;

create table if not exists public.relation_migration_exceptions (
    id bigint generated by default as identity primary key,
    table_name text not null
        check (table_name in ('tasks', 'quests', 'attendance', 'accessibility')),
    row_id bigint not null,
    relation_type text not null
        check (relation_type in ('player', 'project')),
    team_id text,
    legacy_value text,
    reason text not null,
    created_at timestamptz not null default now(),
    unique (table_name, row_id, relation_type)
);

alter table public.relation_migration_exceptions enable row level security;
revoke all on public.relation_migration_exceptions from public, anon, authenticated;
grant all on public.relation_migration_exceptions to service_role;
grant usage, select on sequence public.relation_migration_exceptions_id_seq
    to service_role;

-- Legacy clients resolve relations by team and display name, so that pair must
-- stay unambiguous until every write path sends normalized IDs.
do $$
begin
    if exists (
        select 1 from public.players
        where team_id is not null
        group by team_id, name having count(*) > 1
    ) then
        raise exception 'Duplicate player names exist within a team'
            using errcode = '23505';
    end if;
    if exists (
        select 1 from public.projects
        where team_id is not null
        group by team_id, name having count(*) > 1
    ) then
        raise exception 'Duplicate project names exist within a team'
            using errcode = '23505';
    end if;
end;
$$;

create unique index if not exists players_team_name_uidx
    on public.players (team_id, name);
create unique index if not exists projects_team_name_uidx
    on public.projects (team_id, name);

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'tasks',
        'quests',
        'attendance',
        'accessibility'
    ] loop
        execute format(
            'alter table public.%I add column if not exists player_id bigint',
            table_name
        );

        if not exists (
            select 1
            from pg_constraint constraint_row
            join pg_attribute attribute_row
              on attribute_row.attrelid = constraint_row.conrelid
             and attribute_row.attnum = any (constraint_row.conkey)
            where constraint_row.conrelid = format('public.%I', table_name)::regclass
              and constraint_row.contype = 'f'
              and constraint_row.confrelid = 'public.players'::regclass
              and attribute_row.attname = 'player_id'
        ) then
            execute format(
                'alter table public.%I add constraint %I foreign key (player_id) references public.players(id) on update cascade on delete set null',
                table_name,
                table_name || '_player_id_fkey'
            );
        end if;

        execute format(
            'create index if not exists %I on public.%I (team_id, player_id)',
            table_name || '_team_player_idx',
            table_name
        );
    end loop;

    foreach table_name in array array[
        'tasks',
        'quests',
        'accessibility'
    ] loop
        execute format(
            'alter table public.%I add column if not exists project_id bigint',
            table_name
        );

        if not exists (
            select 1
            from pg_constraint constraint_row
            join pg_attribute attribute_row
              on attribute_row.attrelid = constraint_row.conrelid
             and attribute_row.attnum = any (constraint_row.conkey)
            where constraint_row.conrelid = format('public.%I', table_name)::regclass
              and constraint_row.contype = 'f'
              and constraint_row.confrelid = 'public.projects'::regclass
              and attribute_row.attname = 'project_id'
        ) then
            execute format(
                'alter table public.%I add constraint %I foreign key (project_id) references public.projects(id) on update cascade on delete set null',
                table_name,
                table_name || '_project_id_fkey'
            );
        end if;

        execute format(
            'create index if not exists %I on public.%I (team_id, project_id)',
            table_name || '_team_project_idx',
            table_name
        );
    end loop;
end;
$$;

update public.tasks row_data
set player_id = (
    select min(player.id)
    from public.players player
    where player.team_id = row_data.team_id
      and player.name = row_data.member
)
where row_data.player_id is null
  and row_data.member is not null;

update public.quests row_data
set player_id = (
    select min(player.id)
    from public.players player
    where player.team_id = row_data.team_id
      and player.name = row_data.member
)
where row_data.player_id is null
  and row_data.member is not null;

update public.attendance row_data
set player_id = (
    select min(player.id)
    from public.players player
    where player.team_id = row_data.team_id
      and player.name = row_data.member
)
where row_data.player_id is null
  and row_data.member is not null;

update public.accessibility row_data
set player_id = (
    select min(player.id)
    from public.players player
    where player.team_id = row_data.team_id
      and player.name = row_data.member
)
where row_data.player_id is null
  and row_data.member is not null;

update public.tasks row_data
set project_id = (
    select min(project.id)
    from public.projects project
    where project.team_id = row_data.team_id
      and project.name = row_data.proj
)
where row_data.project_id is null
  and row_data.proj is not null;

update public.quests row_data
set project_id = (
    select min(project.id)
    from public.projects project
    where project.team_id = row_data.team_id
      and project.name = row_data.proj
)
where row_data.project_id is null
  and row_data.proj is not null;

update public.accessibility row_data
set project_id = (
    select min(project.id)
    from public.projects project
    where project.team_id = row_data.team_id
      and project.name = row_data.proj
)
where row_data.project_id is null
  and row_data.proj is not null;

insert into public.relation_migration_exceptions (
    table_name,
    row_id,
    relation_type,
    team_id,
    legacy_value,
    reason
)
select
    unresolved.table_name,
    unresolved.row_id,
    unresolved.relation_type,
    unresolved.team_id,
    unresolved.legacy_value,
    'No matching normalized record at V34 backfill'
from (
    select 'tasks' as table_name, id as row_id, 'player' as relation_type,
        team_id, member as legacy_value
    from public.tasks where member is not null and player_id is null
    union all
    select 'quests', id, 'player', team_id, member
    from public.quests where member is not null and player_id is null
    union all
    select 'attendance', id, 'player', team_id, member
    from public.attendance where member is not null and player_id is null
    union all
    select 'accessibility', id, 'player', team_id, member
    from public.accessibility where member is not null and player_id is null
    union all
    select 'tasks', id, 'project', team_id, proj
    from public.tasks where proj is not null and project_id is null
    union all
    select 'quests', id, 'project', team_id, proj
    from public.quests where proj is not null and project_id is null
    union all
    select 'accessibility', id, 'project', team_id, proj
    from public.accessibility where proj is not null and project_id is null
) unresolved
on conflict (table_name, row_id, relation_type) do update
set team_id = excluded.team_id,
    legacy_value = excluded.legacy_value,
    reason = excluded.reason;

-- Existing FK values are authoritative when a project or player was renamed.
update public.tasks row_data
set member = player.name
from public.players player
where row_data.player_id = player.id
  and row_data.member is distinct from player.name;

update public.quests row_data
set member = player.name
from public.players player
where row_data.player_id = player.id
  and row_data.member is distinct from player.name;

update public.attendance row_data
set member = player.name
from public.players player
where row_data.player_id = player.id
  and row_data.member is distinct from player.name;

update public.accessibility row_data
set member = player.name
from public.players player
where row_data.player_id = player.id
  and row_data.member is distinct from player.name;

update public.tasks row_data
set proj = project.name
from public.projects project
where row_data.project_id = project.id
  and row_data.proj is distinct from project.name;

update public.quests row_data
set proj = project.name
from public.projects project
where row_data.project_id = project.id
  and row_data.proj is distinct from project.name;

update public.accessibility row_data
set proj = project.name
from public.projects project
where row_data.project_id = project.id
  and row_data.proj is distinct from project.name;

create or replace function public.sync_player_reference()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    resolved_player public.players%rowtype;
    legacy_name_changed boolean;
begin
    if tg_op = 'UPDATE' then
        legacy_name_changed := (
            new.member is distinct from old.member
            or new.team_id is distinct from old.team_id
        )
        and new.player_id is not distinct from old.player_id;
    else
        legacy_name_changed := false;
    end if;

    if new.member is null and new.player_id is null then
        delete from public.relation_migration_exceptions
        where table_name = tg_table_name
          and row_id = new.id
          and relation_type = 'player';
        return new;
    end if;

    if tg_op = 'UPDATE'
       and old.player_id is not null
       and new.player_id is null
       and new.member is not distinct from old.member
       and new.team_id is not distinct from old.team_id then
        insert into public.relation_migration_exceptions (
            table_name,
            row_id,
            relation_type,
            team_id,
            legacy_value,
            reason
        ) values (
            tg_table_name,
            new.id,
            'player',
            new.team_id,
            new.member,
            'Normalized player record was removed'
        )
        on conflict (table_name, row_id, relation_type) do update
        set team_id = excluded.team_id,
            legacy_value = excluded.legacy_value,
            reason = excluded.reason;
        return new;
    end if;

    if new.player_id is null or legacy_name_changed then
        select * into resolved_player
        from public.players player
        where player.team_id = new.team_id
          and player.name = new.member
        order by player.id
        limit 1;
    else
        select * into resolved_player
        from public.players player
        where player.id = new.player_id
          and player.team_id = new.team_id;
    end if;

    if not found then
        raise exception 'Player reference is not valid for team %', new.team_id
            using errcode = '23503';
    end if;

    if new.member is not null and new.member is distinct from resolved_player.name then
        raise exception 'Player name does not match player_id for team %', new.team_id
            using errcode = '23503';
    end if;

    new.player_id := resolved_player.id;
    new.member := resolved_player.name;
    delete from public.relation_migration_exceptions
    where table_name = tg_table_name
      and row_id = new.id
      and relation_type = 'player';
    return new;
end;
$$;

create or replace function public.sync_project_reference()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    resolved_project public.projects%rowtype;
    legacy_name_changed boolean;
begin
    if tg_op = 'UPDATE' then
        legacy_name_changed := (
            new.proj is distinct from old.proj
            or new.team_id is distinct from old.team_id
        )
        and new.project_id is not distinct from old.project_id;
    else
        legacy_name_changed := false;
    end if;

    if new.proj is null and new.project_id is null then
        delete from public.relation_migration_exceptions
        where table_name = tg_table_name
          and row_id = new.id
          and relation_type = 'project';
        return new;
    end if;

    if tg_op = 'UPDATE'
       and old.project_id is not null
       and new.project_id is null
       and new.proj is not distinct from old.proj
       and new.team_id is not distinct from old.team_id then
        insert into public.relation_migration_exceptions (
            table_name,
            row_id,
            relation_type,
            team_id,
            legacy_value,
            reason
        ) values (
            tg_table_name,
            new.id,
            'project',
            new.team_id,
            new.proj,
            'Normalized project record was removed'
        )
        on conflict (table_name, row_id, relation_type) do update
        set team_id = excluded.team_id,
            legacy_value = excluded.legacy_value,
            reason = excluded.reason;
        return new;
    end if;

    if new.project_id is null or legacy_name_changed then
        select * into resolved_project
        from public.projects project
        where project.team_id = new.team_id
          and project.name = new.proj
        order by project.id
        limit 1;
    else
        select * into resolved_project
        from public.projects project
        where project.id = new.project_id
          and project.team_id = new.team_id;
    end if;

    if not found then
        raise exception 'Project reference is not valid for team %', new.team_id
            using errcode = '23503';
    end if;

    if new.proj is not null and new.proj is distinct from resolved_project.name then
        raise exception 'Project name does not match project_id for team %', new.team_id
            using errcode = '23503';
    end if;

    new.project_id := resolved_project.id;
    new.proj := resolved_project.name;
    delete from public.relation_migration_exceptions
    where table_name = tg_table_name
      and row_id = new.id
      and relation_type = 'project';
    return new;
end;
$$;

revoke all on function public.sync_player_reference() from public;
revoke all on function public.sync_project_reference() from public;

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'tasks',
        'quests',
        'attendance',
        'accessibility'
    ] loop
        execute format(
            'drop trigger if exists %I on public.%I',
            table_name || '_sync_player_reference',
            table_name
        );
        execute format(
            'create trigger %I before insert or update of team_id, member, player_id on public.%I for each row execute function public.sync_player_reference()',
            table_name || '_sync_player_reference',
            table_name
        );
    end loop;

    foreach table_name in array array[
        'tasks',
        'quests',
        'accessibility'
    ] loop
        execute format(
            'drop trigger if exists %I on public.%I',
            table_name || '_sync_project_reference',
            table_name
        );
        execute format(
            'create trigger %I before insert or update of team_id, proj, project_id on public.%I for each row execute function public.sync_project_reference()',
            table_name || '_sync_project_reference',
            table_name
        );
    end loop;
end;
$$;

create or replace function public.propagate_player_reference_name()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.name is distinct from old.name then
        update public.tasks set member = new.name where player_id = new.id;
        update public.quests set member = new.name where player_id = new.id;
        update public.attendance set member = new.name where player_id = new.id;
        update public.accessibility set member = new.name where player_id = new.id;
    end if;
    return new;
end;
$$;

create or replace function public.prevent_referenced_player_team_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.team_id is distinct from old.team_id
       and (
           exists (select 1 from public.tasks where player_id = old.id)
           or exists (select 1 from public.quests where player_id = old.id)
           or exists (select 1 from public.attendance where player_id = old.id)
           or exists (select 1 from public.accessibility where player_id = old.id)
       ) then
        raise exception 'Referenced player cannot move to another team'
            using errcode = '23503';
    end if;
    return new;
end;
$$;

create or replace function public.propagate_project_reference_name()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.name is distinct from old.name then
        update public.tasks set proj = new.name where project_id = new.id;
        update public.quests set proj = new.name where project_id = new.id;
        update public.accessibility set proj = new.name where project_id = new.id;
    end if;
    return new;
end;
$$;

create or replace function public.prevent_referenced_project_team_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.team_id is distinct from old.team_id
       and (
           exists (select 1 from public.tasks where project_id = old.id)
           or exists (select 1 from public.quests where project_id = old.id)
           or exists (select 1 from public.accessibility where project_id = old.id)
       ) then
        raise exception 'Referenced project cannot move to another team'
            using errcode = '23503';
    end if;
    return new;
end;
$$;

revoke all on function public.propagate_player_reference_name() from public;
revoke all on function public.propagate_project_reference_name() from public;
revoke all on function public.prevent_referenced_player_team_change() from public;
revoke all on function public.prevent_referenced_project_team_change() from public;

drop trigger if exists players_prevent_referenced_team_change on public.players;
create trigger players_prevent_referenced_team_change
before update of team_id on public.players
for each row execute function public.prevent_referenced_player_team_change();

drop trigger if exists projects_prevent_referenced_team_change on public.projects;
create trigger projects_prevent_referenced_team_change
before update of team_id on public.projects
for each row execute function public.prevent_referenced_project_team_change();

drop trigger if exists players_propagate_reference_name on public.players;
create trigger players_propagate_reference_name
after update of name on public.players
for each row execute function public.propagate_player_reference_name();

drop trigger if exists projects_propagate_reference_name on public.projects;
create trigger projects_propagate_reference_name
after update of name on public.projects
for each row execute function public.propagate_project_reference_name();

commit;
