-- V35: additive security primitives that must be installed before the
-- application version that consumes level-up notification events is deployed.

-- A level-up message is valid only when the players.level column actually
-- increases. The API consumes one pending event and cannot replay it.
create table if not exists public.level_up_notification_events (
    id bigint generated by default as identity primary key,
    team_id text not null,
    player_id bigint not null references public.players(id) on delete cascade,
    level integer not null check (level > 0),
    status text not null default 'pending'
        check (status in ('pending', 'sending', 'sent')),
    failure_code text,
    created_at timestamptz not null default now(),
    sent_at timestamptz,
    unique (team_id, player_id, level)
);

create index if not exists level_up_notification_events_pending_idx
    on public.level_up_notification_events (team_id, status, created_at);

alter table public.level_up_notification_events enable row level security;
alter table public.level_up_notification_events force row level security;
revoke all on table public.level_up_notification_events from anon, authenticated;
grant all on table public.level_up_notification_events to service_role;
grant usage, select on sequence public.level_up_notification_events_id_seq
to service_role;

create or replace function public.capture_level_up_notification_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.level is not null
       and old.level is not null
       and new.level > old.level
       and new.team_id is not null then
        insert into public.level_up_notification_events (
            team_id,
            player_id,
            level
        ) values (
            new.team_id,
            new.id,
            new.level
        )
        on conflict (team_id, player_id, level) do nothing;
    end if;
    return new;
end;
$$;

revoke all on function public.capture_level_up_notification_event() from public;

drop trigger if exists players_capture_level_up_notification_event
on public.players;
create trigger players_capture_level_up_notification_event
after update of level on public.players
for each row
execute function public.capture_level_up_notification_event();

-- Keep short-lived failed attempts and delivered claims from accumulating
-- forever. Call this from scheduled maintenance with service_role.
drop function if exists public.purge_expired_agent_security_data();
create or replace function public.purge_expired_agent_security_data()
returns table (
    deleted_level_events bigint,
    deleted_deliveries bigint,
    deleted_suggestions bigint,
    deleted_calendar_events bigint,
    deleted_audit_logs bigint,
    deleted_admin_audit_logs bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
    level_count bigint;
    delivery_count bigint;
    suggestion_count bigint;
    calendar_event_count bigint;
    audit_log_count bigint;
    admin_audit_log_count bigint;
begin
    delete from public.level_up_notification_events
    where created_at < now() - interval '180 days';
    get diagnostics level_count = row_count;

    delete from public.agent_notification_deliveries
    where sent_at < now() - interval '180 days';
    get diagnostics delivery_count = row_count;

    delete from public.agent_suggestions
    where created_at < now() - interval '180 days'
      and status in ('dismissed', 'applied');
    get diagnostics suggestion_count = row_count;

    delete from public.agent_calendar_events
    where synced_at < now() - interval '90 days';
    get diagnostics calendar_event_count = row_count;

    delete from public.audit_logs
    where created_at < now() - interval '365 days';
    get diagnostics audit_log_count = row_count;

    delete from public.admin_audit_logs
    where created_at < now() - interval '365 days';
    get diagnostics admin_audit_log_count = row_count;

    return query select
        level_count,
        delivery_count,
        suggestion_count,
        calendar_event_count,
        audit_log_count,
        admin_audit_log_count;
end;
$$;

revoke all on function public.purge_expired_agent_security_data() from public;
grant execute on function public.purge_expired_agent_security_data() to service_role;
